/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ffae3e54-76de-40ca-9a00-f913a50b5e27",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WuUPY4Zwp",
    "aws_user_pools_web_client_id": "69kn22k9a8tuii410q8fv0hsqk",
    "oauth": {}
};


export default awsmobile;
